---
# tasks/Fedora/rabbit.yml: Deploy RabbitMQ
# Specific to Fedora

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure Erlang & RabbitMQ are installed
    yum:
      name:
        - erlang
        - rabbitmq-server
      state: present
